### ISSUE TITLE
Sometimes the conversion simply don't work

### ISSUE THREAD

**Issue by Alecell** [HadaIonut/Foundry-mgl#14] opened 2021-07-11 23:38 UTC
I'm using D&D5e system.

If I switch from meters to feets and try to metrify again it simply don't work. No errors are logged but nothing happens too.

Maybe its because my foundry version, but is there a plan to update the module?

**Comment by HadaIonut** [comment] 2021-07-12 03:58
Heya, that is intended behavior sadly.

When an item gets metrified it is also marked to not be metrified again. This happens to avoid stuff like converting a range from 30 to 10 and than again to 3.

I have also thought of removing the flag of the item is modified but I don't have a way to do that, so sadly there is nothing I can do

**Comment by Alecell** [comment] 2021-07-12 12:10
Really? I mean, seems like a simple issue, but I don't know how to make foundry plugins anyway.

I'm thinking here, if we just remove the flag and don't use it? The units will be M or FT, so the player can know the current unit, knowing if should or shouldn't convert it.

Also, if I lookout this issue, do you accept PR's?

**Comment by HadaIonut** [comment] 2021-07-12 14:22
The problem is that not all fields mention what unit is assigned to them. Because of that I can never be 100% sure if the value in that field is in ft or m. I could take some guesses but that would allow for weird edge cases that I would like to not deal with. 

But if you think of a way to fix that I am happy to accept your PR.

**Closed as completed by HadaIonut** 2021-07-12 14:22 UTC
